server:
  port: 8081
spring:
  application:
    name: bank-account-service
    title : bank-account-service
  datasource:
    username: 'amigoscode'
    password: 'password'
    url: jdbc:postgresql://localhost:5432/accountservice
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
